# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 11:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('prerequisites', models.CharField(max_length=1000)),
                ('syllabus', models.CharField(max_length=1000)),
                ('payments', models.IntegerField()),
                ('notice', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=1)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentix.Course')),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('type', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contactNo', models.CharField(max_length=10)),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('choice_1', models.CharField(default='', max_length=100)),
                ('choice_2', models.CharField(default='', max_length=100)),
                ('choice_3', models.CharField(default='', max_length=100)),
                ('choice_4', models.CharField(default='', max_length=100)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1)),
                ('status', models.IntegerField(default=1)),
                ('Taken_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentix.Course')),
                ('loginuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentix.LoginUser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentix.Quiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='loginuser',
            field=models.ManyToManyField(through='studentix.Quiz', to='studentix.LoginUser'),
        ),
    ]
