# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentix', '0002_auto_20160305_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
