# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentix', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_term',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='course',
            name='mid_term',
            field=models.IntegerField(default=-1),
        ),
    ]
