# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentix', '0005_auto_20160306_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
