# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentix', '0007_remove_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_term_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='mid_term_score',
            field=models.IntegerField(default=-1),
        ),
    ]
