# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentix', '0008_auto_20160306_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('loginuser_reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentix.LoginUser')),
                ('loginuser_sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
