# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentix', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='loginuser_sender',
            new_name='user_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
